from mik_tools.mik_learning_tools.learning_tools.train_tools.train_tools import train_model
from mik_tools.mik_learning_tools.learning_tools.train_tools.training_callbacks import NormalizationQuickstart
